#服务
server:
  port: 80

#spring相关配置
spring:
   datasource:
      name: darker_pool
      type: com.alibaba.druid.pool.DruidDataSource
      #连接池相关配置
      druid:
        filters: stat
        driver-class-name: com.mysql.jdbc.Driver
        #基本属性信息
        url: jdbc:mysql://127.0.0.1:3306/darker?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        username: root
        password: root
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #最大建立连接等待时间.如果超过此时间将接到异常.设为-1表示无限制,单位是ms
        max-wait: 60000
        #间隔多久进行一次检测,检测需要关闭的空间连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        #验证数据库连接有效性
        validation-query: SELECT '1'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
   redis:
      host: 127.0.0.1
      port: 6379
      password: redis
      pool:
        #最大空闲连接
        max-idle: 100
        #最小空闲连接
        min-idle: 1
        #最大连接数
        max-active: 1000
        #最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      #连接超时时间（毫秒.设置为0,启动失败）
      timeout: 10000
   mvc:
     view:
       prefix: /templates/
       suffix: .html
     static-path-pattern: /**
   thymeleaf:
     cache : false
   application:
     name: spring-boot-rabbitmq-sender
   rabbitmq:
     host: 127.0.0.1
     port: 5672
     username: guest
     password: guest
   data:
     elasticsearch:
       repositories:
         enabled: true
       cluster-nodes: 127.0.0.1:9200
       cluster-name: darker
       properties:
         path:
           home: F:/elasticsearch-6.5.4/data/project/target/elastic
         transport:
           tcp:
             connect_timeout: 120s
mybatis-plus:
  #VO扫描路径
  type-aliases-package: com.vip.darker.entity
  global-config:
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

#分页
pagehelper:
  helperDoalect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

#常量值
statistics:
  #记录浏览量
  countPV: 1000
  #记录访问量
  countVV: 500
  #记录访问人数
  countUV: 235

#线程池
pool:
  #最少数量
  core-pool-size: 5
  #最大数量
  max-pool-size: 10
  #缓存队列量
  queue-capacity: 20
  #允许的空闲时间(秒)
  keep-alive-seconds: 60